#:import Grafico app.classes.grafico
#:import TopBar app.classes.topbar
#:import App kivy.app

<Grafico>:
    grafico: grafico

    GridLayout:
        orientation: 'vertical'
        cols: 1

        canvas.before:
            Color:
                rgba: utils.get_color_from_hex('#41704d')
            Rectangle:
                size:self.size
                pos:self.pos

        TopBar:

        Image:
            id: grafico
            source: f'{app.user_data_dir}/grafico.png'
