<Tela>:
    cols: 1
    display: display
    information: information
    orientation: 'vertical'

    Label:
        id: information
        size_hint: (1, 0.3)
        text: 'tetsetete'
        font_name: 'assets/fonts/times new.ttf'
        font_size: 24


    Label:
        id: display
        text: 'banana'
        font_name: 'assets/fonts/times new.ttf'
        font_size: 54
        height: 5
